#!/bin/bash

do_start() {
    echo "$0 start"
    test -x /usr/bin/brightness-setup.sh && /usr/bin/brightness-setup.sh
}

do_stop() {
    echo "$0 stop"
}

case "$1" in
    start)
    	do_start
        ;;
    stop)
        do_stop
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 3
        ;;
esac
exit 0
