## zzstumpwm zwm

services:
  zwm:
    build:
      context: ../dockerfiles
      dockerfile: ubuntu-dev.dockerfile
      args:
        VARIANT: 22.04
    image: zhoujd/ubuntu-22.04-zwm:dev
    hostname: ubuntu-2204-zwm
    container_name: zwm-dev
    environment:
      DISPLAY:
      ZWM_DSP:
      ZWM_REZ:
      GITLAB_TOKEN:
      GITHUB_TOKEN:
    network_mode: bridge
    command: xephyr
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /etc/sysctl.conf:/etc/sysctl.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/work/:/home/${USER}/work
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - ${ZWM_ROOT}:/home/${USER}/zzstumpwm
      - ${ZWM_TOP}/zzemacs:/home/${USER}/zzemacs
      - /opt/zach/zwm/.ssh:/home/${USER}/.ssh
      - /opt/zach/zwm/.local:/home/${USER}/.local
      - /opt/zach/zwm/.config:/home/${USER}/.config
      - /opt/zach/zwm/.emacs.d:/home/${USER}/.emacs.d
      - /opt/zach/zwm/.vscode:/home/${USER}/.vscode
