version: "3"

services:
  zwm:
    build:
      context: ../dockerfiles
      dockerfile: ubuntu-dev.dockerfile
      args:
        VARIANT: 20.04
    image: zz/ubuntu-20.04-zwm:dev
    hostname: ubuntu-2004-zwm
    container_name: zwm-dev
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: bridge
    command: Xephyr ${XR_DSP} -ac -br -screen ${XR_REZ} -resizeable
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
