version: "3"

services:
  zwm:
    build:
      context: ../dockerfiles
      dockerfile: ubuntu-dev.dockerfile
      args:
        VARIANT: 20.04
    image: zz/ubuntu-20.04-zwm:dev
    hostname: ubuntu-2004-zwm
    container_name: zwm-dev
    environment:
      DISPLAY:
      ZWM_DSP:
      ZWM_REZ:
      GITLAB_TOKEN:
      GITHUB_TOKEN:
      XMODIFIERS:
      QT_IM_MODULE:
      GTK_IM_MODULE:
    network_mode: bridge
    command: xephyr
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /etc/sysctl.conf:/etc/sysctl.conf
      - /etc/localtime:/etc/localtime:ro
      - ${ZWM_ROOT}:/home/${USER}/zzstumpwm
      - ${ZWM_TOP}/zzemacs:/home/${USER}/zzemacs
      - ${ZWM_TOP}/lab:/home/${USER}/lab
      - ${ZWM_TOP}/.zwm/.ssh:/home/${USER}/.ssh
      - ${ZWM_TOP}/.zwm/.local:/home/${USER}/.local
      - ${ZWM_TOP}/.zwm/.config:/home/${USER}/.config
      - ${ZWM_TOP}/.zwm/.emacs.d:/home/${USER}/.emacs.d
      - ${ZWM_TOP}/.zwm/.vscode:/home/${USER}/.vscode
