version: "3"

services:
  zwm:
    build:
      context: ../dockerfiles
      dockerfile: ubuntu-dev.dockerfile
      args:
        VARIANT: 20.04
    image: zz/ubuntu-20.04-zwm:dev
    hostname: ubuntu-2004-zwm
    container_name: zwm-dev
    environment:
      DISPLAY: ${DISPLAY}
      ZWM_DSP: ${ZWM_DSP}
      ZWM_REZ: ${ZWM_REZ}
    network_mode: bridge
    entrypoint:
      - /app/entrypoint.sh
      - xephyr
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /etc/sysctl.conf:/etc/sysctl.conf
      - ${ZWM_ROOT}:/home/${USER}/zzstumpwm
      - ${ZWM_TOP}/zzemacs:/home/${USER}/zzemacs
      - ${ZWM_TOP}/lab:/home/${USER}/lab
