version: "3"

services:
  zwm:
    build:
      context: ../dockerfiles
      dockerfile: ubuntu-dev.dockerfile
      args:
        VARIANT: 20.04
    image: zhoujd/ubuntu-20.04-zwm:dev
    hostname: ubuntu-2004-zwm
    container_name: zwm-dev
    environment:
      DISPLAY:
      ZWM_DSP:
      ZWM_REZ:
      GITLAB_TOKEN:
      GITHUB_TOKEN:
    network_mode: bridge
    command: xephyr
    extra_hosts:
      - "myhost:host-gateway"
    restart: always
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /etc/sysctl.conf:/etc/sysctl.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${ZWM_ROOT}:/home/${USER}/zzstumpwm
      - ${ZWM_TOP}/zzemacs:/home/${USER}/zzemacs
      - /opt/zwm/lab:/home/${USER}/lab
      - /opt/zwm/.ssh:/home/${USER}/.ssh
      - /opt/zwm/.local:/home/${USER}/.local
      - /opt/zwm/.config:/home/${USER}/.config
      - /opt/zwm/.emacs.d:/home/${USER}/.emacs.d
      - /opt/zwm/.vscode:/home/${USER}/.vscode
