language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get install info install-info
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - cl -l alexandria -l clx -l cl-ppcre -l fiasco -e '(ql-util:without-prompting (ql:add-to-init-file))'

before_script:
  - ./autogen.sh
  - ./configure

script:
  - make travis

notifications:
  irc: "chat.freenode.net#stumpwm"
  urls:
          - https://webhooks.gitter.im/e/c1294f93beaf1b4f4f51
    on_success: change
    on_failure: always
    on_start: never
  email:
    on_success: never
    on_failure: always
