#!/usr/bin/env bash

WIDTH=20
SEL=$((echo new; echo new default; tmux list-session -F '#S') | rofi -dmenu -p "Tmux Session:" -width $WIDTH)
TERM=urxvt  ##rofi-sensible-terminal

if [[ x"new" = x"${SEL}" ]]; then
    SID=$(echo -en "" | rofi -dmenu -p "Session:" -mesg "Enter the Session Name" -lines 0)
    if [[ "$SID" != ''  ]]; then
        ${TERM} -e tmux new-session -s ${SID} &
    fi
elif [[ x"new default" = x"${SEL}" ]]; then
    ${TERM} -e tmux new-session &
elif [[ -z "${SEL}" ]]; then
    echo "Cancel"
else
    ${TERM} -e tmux attach -t "${SEL}" &
fi
