#!/usr/bin/env bash

TMUX_SESSION=$((echo new; tmux list-session -F '#S') | rofi -dmenu -p "Tmux Session:")
TERM_SELECT=urxvt  ##rofi-sensible-terminal

if [[ x"new" = x"${TMUX_SESSION}" ]]; then
    SID=$(echo -en "" | rofi -dmenu -p "Session:" -mesg "Enter the Session Name" -lines 0)
    if [[ "$SID" != ''  ]]; then
        ${TERM_SELECT} -e tmux new-session -s ${SID} &
    fi
elif [[ -z "${TMUX_SESSION}" ]]; then
    echo "Cancel"
else
    ${TERM_SELECT} -e tmux attach -t "${TMUX_SESSION}" &
fi
