#!/bin/bash

pid_file=/tmp/screen-record-pid
default_file=/tmp/record.mkv

start() {
    if [ $# != 1 ]; then
        echo "Usage: $(basename $0) start {file}"
        exit 1
    fi
    
    echo "record start"
    file=$1
    read -r x y w h G ID < <(slop -f '%x %y %w %h %g %i')
    if [ -z $G ]; then
        echo "slop cancelled"
        exit 1
    fi
    echo "recording x:$x, y:$y, w:$w, h:$h, file:$file"
    exec ffmpeg -y \
         -f x11grab \
         -s ${w}x${h} \
         -framerate 30 \
         -i $DISPLAY+${x},${y} \
         ${file} &
    pid=$!
    echo $pid > $pid_file
}

## To stop recording, make the terminal active and then press q.
## kill the ffmpeg process with SIGINT
stop() {
    echo "record stop"
    if [ -f $pid_file ]; then
        kill -SIGINT $(cat $pid_file)
        rm -f $pid_file
    else
        echo "no exist recording"
    fi
}

status() {
    echo "record status"
    if [ -f $pid_file ]; then
        cat $pid_file
    else
        echo "no exist recording"
    fi
}

toggle() {
    if [ -f $pid_file ]; then
        stop
    else
        echo "record to $default_file"
        start $default_file
    fi
}

case $1 in
    start )
        start $2
        ;;
    stop )
        stop
        ;;
    status )
        status
        ;;
    toggle )
        toggle
        ;;
    * )
        echo "Usage $(basename $0) {start|stop|status|toggle}"
        exit 1
        ;;
esac
