#!/bin/bash

pid_file=/tmp/screen-record-pid
default_file=/tmp/record.mkv
log_file=/tmp/record.log

deps() {
    echo "install deps"
    sudo apt install slop ffmpeg mpv
}

region() {
    echo "record select"
    file=${1:-$default_file}
    read -r x y w h G ID < <(slop -f '%x %y %w %h %g %i')
    if [ -z $G ]; then
        echo "slop cancelled"
        exit 1
    fi
    echo "recording x:$x, y:$y, w:$w, h:$h, file:$file"
    exec ffmpeg -y \
         -f x11grab \
         -s ${w}x${h} \
         -framerate 30 \
         -i $DISPLAY+${x},${y} \
         ${file} \
         2>$log_file &
    pid=$!
    echo $pid > $pid_file
}

screen() {
    echo "record screen"
    file=${1:-$default_file}
    x=0
    y=0
    rez=$(xdpyinfo | awk '/dimensions/{print $2}')
    echo "recording x:${x}, y:${y}, rez:$rez, file:$file"
    exec ffmpeg -y \
         -f x11grab \
         -s ${rez} \
         -framerate 30 \
         -i $DISPLAY+${x},${y} \
         ${file} \
         2>$log_file &
    pid=$!
    echo $pid > $pid_file
}

## To stop recording, make the terminal active and then press q.
## kill the ffmpeg process with SIGINT
stop() {
    echo "record stop"
    if [ -f $pid_file ]; then
        kill -SIGINT $(cat $pid_file)
        rm -f $pid_file
    else
        echo "no exist recording"
    fi
}

status() {
    echo "record status"
    if [ -f $pid_file ]; then
        cat $pid_file
    else
        echo "no exist recording"
    fi
}

toggle() {
    if [ -f $pid_file ]; then
        stop
    else
        echo "record to $default_file"
        region
    fi
}

full() {
    if [ -f $pid_file ]; then
        stop
    else
        echo "screen record to $default_file"
        screen
    fi
}

play() {
    if [ -f $default_file ]; then
        mpv $default_file
    else
        echo "no exist $default_file"
    fi
}

usage() {
    echo "Usage: $(basename $0) {deps|region|screen|stop|status|toggle|full|play}
    deps             install deps (slop/ffmpeg/mpv)
    region {file}    select recording
    screen {file}    full screen recording
    stop             stop recording
    status           status of recording
    toggle           the switch for recording
    full             the switch for full screen recording
    play             playback the recording file $default_file"
}

case $1 in
    deps )
        deps
        ;;
    region )
        region $2
        ;;
    screen )
        screen $2
        ;;
    stop )
        stop
        ;;
    status )
        status
        ;;
    toggle )
        toggle
        ;;
    full )
        full
        ;;
    play )
        play
        ;;
    * )
        usage
        ;;
esac
