#!/bin/bash

case $1 in
    dep )
        ## https://github.com/naelstrof/maim
        sudo apt install -y maim
        ;;
    full )
        maim -u | xclip -selection clipboard -t image/png        
        echo "Screenshot fullscreen to clipboard"
        ;;
    region )
        maim -u -s | xclip -selection clipboard -t image/png        
        echo "Screenshot region to clipboard"
        ;;
    window )
        maim -u -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
        echo "Screenshot window to clipboard"
        ;;
    * )
        echo "Usage: $(basename $0) {dep|full|region|window}"
        ;;
esac
