#!/bin/bash

## https://github.com/naelstrof/maim

PIC=~/Pictures/screenshots
FILE=$(date +%b%d-%H%M%S.png)
WINDOW=$(xdotool getactivewindow)

case $1 in
    dep )
        sudo apt install -y maim
        ;;
    full )
        mkdir -p $PIC
        maim -u  $PIC/$FILE
        echo "Screenshot fullscreen: $PIC/$FILE"
        ;;
    region )
        mkdir -p $PIC
        maim -u -s $PIC/$FILE
        if [ $? = 0 ]; then
            echo "Screenshot region: $PIC/$FILE"
        else
            echo "Screenshot region abort"
        fi
        ;;
    window )
        mkdir -p $PIC
        maim -u -i $WINDOW $PIC/$FILE
        echo "Screenshot window: $PIC/$FILE"
        ;;
    * )
        echo "Usage: $(basename $0) {dep|full|region|window}"
        ;;
esac
