#!/usr/bin/env bash

tmux_sessions() {
    tmux list-session -F '#S'
}

TMUX_SESSION=$((echo new; tmux_sessions) | rofi -dmenu -p "Tmux Session:")
TERM_SELECT=urxvt  ##rofi-sensible-terminal

if [[ x"new" = x"${TMUX_SESSION}" ]]; then
    ${TERM_SELECT} -e tmux new-session &
elif [[ -z "${TMUX_SESSION}" ]]; then
    echo "Cancel"
else
    ${TERM_SELECT} -e tmux attach -t "${TMUX_SESSION}" &
fi
