#!/bin/bash
##https://wiki.archlinux.org/index.php/Touchpad_Synaptics

declare -i ID
ID=`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`

on() {
    xinput enable $ID
    echo "Touchpad enabled."
}

off() {
    xinput disable $ID
    echo "Touchpad disabled."
}

toggle() {
    declare -i STATE
    STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`
    if [ $STATE -eq 1 ]
    then
        off
    else
        on
    fi
}

case $1 in
    on )
        on
        ;;
    off )
        off
        ;;
    * )
        toggle
        ;;
esac
