#!/bin/bash
##https://wiki.archlinux.org/index.php/Touchpad_Synaptics

declare -i ID
ID=`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`

toggle() {
    declare -i STATE
    STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`
    if [ $STATE -eq 1 ]
    then
        xinput disable $ID
        echo "Touchpad disabled."
    else
        xinput enable $ID
        echo "Touchpad enabled."
    fi
}

on() {
    xinput enable $ID
    echo "Touchpad enabled."

}

off() {
    xinput disable $ID
    echo "Touchpad disabled."
}

case $1 in
    on )
        on
        ;;
    off )
        off
        ;;
    * )
        toggle
        ;;
esac
